# robot_shared/cmake/modules/DetectGLFW.cmake
include_guard(GLOBAL)
include(${CMAKE_CURRENT_LIST_DIR}/../core/ColorMessage.cmake)

if (USE_GLFW)
    set(GLFW_LOCAL_PATH "${CMAKE_CURRENT_LIST_DIR}/../../library/glfw/lib/${CURRENT_PLATFORM}")
    if (EXISTS "${GLFW_LOCAL_PATH}")
        set(USE_GLFW ON)
        color_message(STATUS cyan "[INFO] GLFW found in local library: ${GLFW_LOCAL_PATH}")
    else()
        set(USE_GLFW OFF)
        color_message(STATUS yellow "[WARN] GLFW not found - disable GLFW support")
    endif()
else()
    set(USE_GLFW OFF)
    color_message(STATUS cyan "[INFO] GLFW manually disabled.")
endif()
