# DetectQt.cmake
include_guard(GLOBAL)
include(${CMAKE_CURRENT_LIST_DIR}/../core/ColorMessage.cmake)

if(USE_QT)
    find_package(QT QUIET NAMES Qt6 Qt5 COMPONENTS Widgets Network)
    if(QT_FOUND)
        find_package(Qt${QT_VERSION_MAJOR} QUIET COMPONENTS Widgets Network)
        if(TARGET Qt${QT_VERSION_MAJOR}::Widgets AND TARGET Qt${QT_VERSION_MAJOR}::Network)
            set(USE_QT ON)
            color_message(STATUS cyan "[INFO] Qt${QT_VERSION_MAJOR} found, enabling Qt support.")
        else()
            set(USE_QT OFF)
            color_message(STATUS yellow "[INFO] Qt${QT_VERSION_MAJOR} not found, disabling Qt support.")
        endif()
    endif()
endif()

if(USE_QT)
    color_message(STATUS cyan "[INFO] Enabling Qt support.")
else()
    color_message(STATUS cyan "[INFO] Qt support disabled.")
endif()