# robot_shared/cmake/modules/DetectTorch.cmake
include_guard(GLOBAL)
include(${CMAKE_CURRENT_LIST_DIR}/../core/ColorMessage.cmake)

if (USE_TORCH)
    if (DEFINED ENV{LIBTORCH_DIR} AND EXISTS "$ENV{LIBTORCH_DIR}")
        set(CMAKE_PREFIX_PATH $ENV{LIBTORCH_DIR} ${CMAKE_PREFIX_PATH})
        find_package(Torch QUIET)
        if (Torch_FOUND)
            color_message(STATUS cyan "[INFO] LibTorch found at $ENV{LIBTORCH_DIR}")
        else()
            color_message(STATUS cyan "[INFO] LibTorch not found in $ENV{LIBTORCH_DIR}, fallback to CUDA-only mode.")
            set(USE_TORCH OFF)
        endif()
    else()
        color_message(STATUS cyan "[INFO] LIBTORCH_DIR not set, skipping Torch integration.")
        set(USE_TORCH OFF)
    endif()
else()
    color_message(STATUS cyan "[INFO] Torch manually disabled.")
endif()